// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'dbModels/spending_entry_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 8560210450077052426),
      name: 'SpendingEntry',
      lastPropertyId: const IdUid(3, 909106519423985789),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7195425436018089589),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 9070935246921026076),
            name: 'caption',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 909106519423985789),
            name: 'value',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 8560210450077052426),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    SpendingEntry: EntityDefinition<SpendingEntry>(
        model: _entities[0],
        toOneRelations: (SpendingEntry object) => [],
        toManyRelations: (SpendingEntry object) => {},
        getId: (SpendingEntry object) => object.id,
        setId: (SpendingEntry object, int id) {
          object.id = id;
        },
        objectToFB: (SpendingEntry object, fb.Builder fbb) {
          final captionOffset = fbb.writeString(object.caption);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, captionOffset);
          fbb.addInt64(2, object.value);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = SpendingEntry()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..caption = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..value =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [SpendingEntry] entity fields to define ObjectBox queries.
class SpendingEntry_ {
  /// see [SpendingEntry.id]
  static final id =
      QueryIntegerProperty<SpendingEntry>(_entities[0].properties[0]);

  /// see [SpendingEntry.caption]
  static final caption =
      QueryStringProperty<SpendingEntry>(_entities[0].properties[1]);

  /// see [SpendingEntry.value]
  static final value =
      QueryIntegerProperty<SpendingEntry>(_entities[0].properties[2]);
}
